spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
  grpc:
    server:
      port: 9091

server:
  port: 8082


logging:
  level:
    org.springframework.grpc: DEBUG
