spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5435/postgres
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: file:kitchen-server/.env[.properties]
server:
  port: 8085

facility:
  id: ${KITCHEN_FACILITY_ID}