#server:
#  port: 8090
#
#spring:
#  application:
#    name: client-server
#
#  security:
#    oauth2:
#      client:
#        registration:
#          zxc-client:
#            client-id: zxc-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: read
#            provider: spring
#        provider:
#          spring:
#            issuer-uri: http://localhost:9000
##            authorization-uri: http://localhost:9000/oauth2/authorize
##            token-uri: http://localhost:9000/oauth2/token
##            user-info-uri: http://localhost:9000/userinfo
#
logging:
  level:
    org.springframework.security.oauth2.client: debug
    org.springframework.security.oauth2.core: debug
    org.springframework.security.web: debug

server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        provider:
          platform-auth-server:
            issuer-uri: http://127.0.0.1:9000
        registration:
          zxc-client:
            provider: platform-auth-server
            client-id: zxc-client
            client-secret: "secret1"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/zxc-client
            scope:
              - openid
              - profile
              - email
